### ISSUE TITLE
Incompatible dependency in gulp-svg-sprite

### ISSUE THREAD

**Issue by stephanieerin** [ozone-development/ozp-icons#3]
After doing a fresh `npm install` on the repo you'll end up with `svg-sprite` version 2.6 which is not compatible with the other dependencies. The problem stems from the dependency on `gulp-svg-sprite` which doesn't enforce only compatible versions of `svg-sprite`.

**Comment by wski** [comment]
which version of `svg-sprite` fixes this again?

**Comment by clarkjefcoat** [comment]
Moving to "Done" as this is not end-user testable
